options:
    formatter: compact
files:
    include: 'sigma/assets/css/**/*.s+(a|c)ss'
rules:
    # Extends
    extends-before-mixins: 1
    extends-before-declarations: 1
    placeholder-in-extend: 1

    # Mixins
    mixins-before-declarations: 1

    # Line Spacing
    one-declaration-per-line: 2
    empty-line-between-blocks: 2
    single-line-per-selector: 0

    # Disallows
    no-color-keywords: 0
    no-color-literals: 0
    no-css-comments: 0
    no-debug: 2
    no-duplicate-properties: 2
    no-empty-rulesets: 2
    no-extends: 0
    no-ids: 0
    no-important: 0
    no-invalid-hex: 2
    no-mergeable-selectors: 2
    no-misspelled-properties: 2
    no-qualifying-elements: 0
    no-trailing-zero: 2
    no-transition-all: 2
    no-url-protocols: 0
    no-vendor-prefixes: 0
    no-warn: 2
    property-units: 0

    # Nesting
    force-attribute-nesting: 0
    force-element-nesting: 0
    force-pseudo-nesting: 0

    # Name Formats
    class-name-format:
        - 2
        - ignore:
          - MathJax_SVG
          - MathJax
    function-name-format: 2
    id-name-format: 2
    mixin-name-format: 2
    placeholder-name-format: 2
    variable-name-format: 2

    # Style Guide
    bem-depth: 0
    border-zero:
        - 2
        - convention: none
    brace-style: 2
    clean-import-paths: 2
    empty-args: 2
    hex-length: 2
    hex-notation: 2
    indentation:
        - 2
        - size: 4
    leading-zero: 1
    nesting-depth: 3
    property-sort-order: 0
    quotes: 0
    shorthand-values: 0
    url-quotes: 2
    variable-for-property: 2
    zero-unit: 0

    # Inner Spacing
    space-after-comma: 2
    space-before-colon: 2
    space-after-colon: 2
    space-before-brace: 2
    space-before-bang: 2
    space-after-bang: 2
    space-between-parens: 2
    space-around-operator: 2

    # Final Items
    trailing-semicolon: 2
    final-newline: 2
